name: Publish DLC Builder macOS

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Run publish script
      env:
        github_token: ${{ secrets.CI_GITHUB_TOKEN }}
      run: dotnet fsi publish_mac.fsx
